spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  thymeleaf:
    prefix : classpath:/static/
    suffix : .html
    cache: false
  devtools:
    livereload:
      enabled: true
  messages:
    basename: messages

mybatis:
  type-aliases-package: com.example.restapiboard.vo
  mapper-locations: mybatis/mapper/**/*.xml
