spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql


mybatis:
  type-aliases-package: com.example.restapiboard.vo
  mapper-locations: mybatis/mapper/**/*.xml