INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('1등', 'yum', '1등이당ㅎㅎ', 10, 2, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('둘둘', 'heum', '비추가 많아서 베스트 게시판에 못감', 110, 101, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('와타시와 산반메', 'chanan', '니들 다 뭐하냐 ㅉㅉ', 15, 12, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('넘버 포', 'park', 'this is content4', 0, 0, CURRENT_TIME());

INSERT INTO  BOARD(TITLE, AUTHOR, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES ('다섯번째 글이다', 'llshl', '베스트 게시판은 내꺼', 115, 2, CURRENT_TIME());


INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('qwer', 'pass', 'lsh970708@naver.com', '이승현', 'llshl');

INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('asdf', 'pass1', 'asdf@naver.com', '조영흠', 'heum');

INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('zxcv', 'pass2', 'zxcv@naver.com', '염찬영', 'yum');

INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('rr', 'pass3', 'rr@naver.com', '김도근', 'dogun');

INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('ff', 'pass4', 'ff@naver.com', '오해찬', 'ohgreen');

INSERT INTO MEMBER(LOGIN_ID, LOGIN_PASSWORD, EMAIL, NAME, NICKNAME)
VALUES ('vv', 'pass5', 'vv@naver.com', '박찬환', 'chanan');


INSERT INTO COMMENT(BOARD_ID, MEMBER_ID, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES (3, 2, '인정 인정', 0, 0, CURRENT_TIME());

INSERT INTO COMMENT(BOARD_ID, MEMBER_ID, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES (3, 1, '맞는 말이지', 75, 3, CURRENT_TIME());

INSERT INTO COMMENT(BOARD_ID, MEMBER_ID, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES (5, 1, '노잼', 3, 415, CURRENT_TIME());

INSERT INTO COMMENT(BOARD_ID, MEMBER_ID, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES (2, 4, '여긴 댓글이 왜 없냐?',111 , 1, CURRENT_TIME());

INSERT INTO COMMENT(BOARD_ID, MEMBER_ID, CONTENT, LIKE_COUNT, DISLIKE_COUNT, DATE)
VALUES (4, 3, '좋아요 20개 감사합니다ㅎㅎ', 21, 1, CURRENT_TIME());